spring:
  application:
    name: scm

springdoc:
  swagger-ui:
    disable-swagger-default-url: true   #디폴트 페이지 안나오게
    path: /api-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true
  default-produces-media-type: application/json
